version: 2
jobs:
  build:
    working_directory: /tmp/server
    docker:
      - image: circleci/python:2.7
      - image: circleci/node:8.10.0
    steps:
      - checkout
      - run:
          name: Install awscli
          command: sudo pip install awsebcli --upgrade
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - run:
          name: Deploy to EB if branch is Master
          command: |
            eb use ms-bike
            eb deploy -v --staged
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules